#include "zbPrint.h"

void intro() {
	zbPrint(L"A simple makefile consists of “rules” with the following shape:\n\n");
	zbPrint(L"\ttarget ... : prerequisites ...\n");
	zbPrint(L"\t\trecipe\n\t\t...\n\t\t...\n\n");
	zbPause();
	zbPrint(L"A target is usually the name of a file that is generated by a program\n");
	zbPrint(L"A prerequisite is a file that is used as input to create the target.\n");
	zbPrint(L"A recipe is an action that make carries out.\n");
	zbPause();
}

void how() {
	zbPrint(L"1. By default, make starts with the first target\n");
	zbPause();
	zbPrint(L"2. recursively process dependences\n");
	zbPause();
	zbPrint(L"3. The other rules are processed if their\n   targets appear as prerequisites of the goal\n\n");
	zbPause();
	zbPrint(L"Rule:\tif the target file does not exist\n");
	zbPrint(L"\tor if any of the prerequisites are newer than it");
	zbPause();
}

int main() {
	zbInit();
	zbTick(40000);
	zbTitle(L"make");
	intro();
	zbClear();
	how();
	
	zbStart();
	zbExit();

}
